name: auto-deploy with docker
on:
  push:
    branches:
      - main
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: git 레파지 복사
        uses: actions/checkout@v4

      - name: jdk 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application 실행 파일 빌드
        run: chmod +x ./gradlew && ./gradlew clean build

      - name: docker 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_USER }}/web-app:latest .

      - name: docker 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: docker hub push
        run: docker push ${{ secrets.DOCKER_USER }}/web-app:latest

  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name:  EC2에 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            docker stop myweb || true
            docker rm myweb || true
            docker pull ${{ secrets.DOCKER_USER }}/web-app:latest
            docker run -d --name myweb -p 8080:8080 ${{ secrets.DOCKER_USER }}/web-app:latest
